title: Chi Zhang
position: Assistant Professor
affiliation: Westlake University 
email: chizhang (at) westlake (dot) edu (dot) cn
keywords: minimal academic
google_scholar: https://scholar.google.com.sg/citations?user=J4s398EAAAAJ&hl
github_link: https://github.com/icoz69
linkedin: https://www.linkedin.com/in/zhang-chi-835a20184/
avatar: ./assets/img/Picture1.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
